# Generated by Django 3.2.19 on 2023-06-24 15:15

from django.db import migrations, models
import immunity_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('test_project', '0004_sheft_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationRadiusSettings',
            fields=[
                (
                    'id',
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'is_active',
                    immunity_utils.fields.FallbackBooleanChoiceField(
                        blank=True, default=None, fallback=False, null=True
                    ),
                ),
                (
                    'is_first_name_required',
                    immunity_utils.fields.FallbackCharChoiceField(
                        blank=True,
                        choices=[
                            ('disabled', 'Disabled'),
                            ('allowed', 'Allowed'),
                            ('mandatory', 'Mandatory'),
                        ],
                        fallback='disabled',
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    'greeting_text',
                    immunity_utils.fields.FallbackCharField(
                        blank=True,
                        fallback='Welcome to Immunity!',
                        max_length=200,
                        null=True,
                    ),
                ),
                (
                    'password_reset_url',
                    immunity_utils.fields.FallbackURLField(
                        blank=True,
                        fallback='http://localhost:8000/admin/password_change/',
                        null=True,
                    ),
                ),
                (
                    'extra_config',
                    immunity_utils.fields.FallbackTextField(
                        blank=True, fallback='no data', max_length=200, null=True
                    ),
                ),
            ],
        ),
    ]
